# Evidence-based Medicine

## Introduction to EBM and Critical Appraisal

Adanya gap antara hasil penelitian dengan praktek sehari hari

ODDS Ratio: rasio terjadinya outcome pada kelompok dgn faktor risiko dengan tidak terjadinya outcome pada kelompok tersebut.

How EBM help: membantu informasi baru, memberikan data empiris dan patien bisa berpartisipasi dalam decision, reduce litigation, keep up to date.

Interpretasi OR: \< 1, misal 0,6 : risiko 60% kali dibandingkan kontrol, mengurangi risiko 40% (berapa dari 1) Interpretasi OR: \> 1, misal 1,5 : risiko 150% atau 1,5 kali lebih besar pada klpk perlakuan, menambah risiko 50%

High sensitivity, if negative, rule out (SnNout) High spesifisity, if positive, rule in (SpPin)

STeps in EBM

1.  Formulate an answerable question

2.  Track down the best evidence of outcomes available

3.  Critically appraise the evidence

4.  Apply the evidence

3 prinsip EBM: 1. Valid\
2. Penting (penting secara klinis dan bermakna secara statistik: hasil, lihat PR, OR, RR,ARR, NNT, mean difference) 3. Aplikabel - Feasible? - kebutuhan lain yg dubutuhkan untuk memanfaatkan evidence? - Alternatif ada? - kemiripan sampel dan pasien kita? - benefit outweight risk? - Bagaiaman tanggapan pasien?

f method untuk estimasi risiko pasien. NNT pada trial dibagi NNT pada pasien kita.

5.  Evaluate our performance

-   evaluasi informal dan formal.

## Clinical Question berdasarkan PICO

memecahkan masalah klinis dengan pendekatan...

### Step 1

proses EBM dimulai dengan skenario klinis yang memerlukan jawaban terbaik berdasarkan bukti ilmiah yang terbaik. "mengubah suatu masalah klinis menjadi masalah reseaarch"

-   Background question: general knowledge (a question root & disorder and other aspect of health care.), dicari dari litrev
-   Foreground question: pertanyaan pengetahuan spesifik untuk menentukan pilihan terapi tau tindakan. Penting menggunakan PICO

**P**: patient, population, problem **I** : intervensi, exposure **C**: control, comparator **O**: outcome, eficacy

Clinical problem = belum sistematis, clinical question= sesuai komponen PICO, dan answerable question.

Contoh: kejang pada pasien 15 tahun, dengan demam. pertanyaan klinis yang mungkin muncul: - apa penyebab demam? - penyebab kejang? - obat terbaik?

lalu masing masing pertanyaan diubah menjadi komponen PICO. umpama, pada pasien anak, apakah pemeriksaan lumbal pungsi lebih baik dari pemeriksaan DL dalam diagnosis DL??

COntoh 2: anak, 8 tahun, dirawat di PICO dengan severe GBS dan menggunakan ventilator. Pengathuan dasar ada terapi prednison, plasma exchange and other. apakah IVIG therapy deliver outcome better than other therapy? =\> Clinical Problem.

PICO: P: child with sever GBS I/C: prednisone, IVIG, atau plasma exchange O: cepat kesembuhan

**good, clear and focused**

### Prinsip Dasar Searching

boelean logic: AND, OR, NOT

**Tugas mencari permasalahan klinis, ubah menjadi pertanyaan research, lalu search dengan Boolean logic di Pubmed** : https://wiryadana.github.io/picolo/

## Effect Size, Hypothesis, and Confidence Interval

besarnya efek: suatu perbedaan klinisdisbeut juga point estimate. Contoh: Rasio prevalens, risiko relative, rasio odds, beda rerata.

ada 4 kemungkinan, - secara statistik signifikan, secara klinis signifikan - secara statistik signifikan, secara klinis tidak signifikan - secara statistik tidak signifikan, secara klinis signifikan - secara statistik tidak signifikan, secara klinis tidak signifikan.

Sebagai klinisi kita mengutamakan clinically important dengan desain yang valid.

Hipotesis positif = adanya hubungan, perbedaan terkecil yang secara klinis yang dianggap penting. hipotesis negatif = tidak ada hubungan, perbedaan terbesar yang secara klinis tidak dianggap penting (non-inferiority)

Contoh: sebuah jurnal melaporkan ksesmbuhan obat A 80%, obat B 55%. Jika melakukan penelitian ulang, maka tidak dibenarkan menggunakan angka 25% sebagai effect size, ada 2 alasan.

1.  alasan konseptual, kenapa harus diulang jika sudah ada nilai 25%
2.  alasan teknis, jika efek size ternyata 23, maka bisa secara statistik tidak signifikan, padahal masih bermakna klinis.

Oleh sebab itu, penentuan efek size adalah judgement peneliti, tidak boleh dari penelitian orang lain.

Untuk generalisasi atau inferensi ke populasi asal sampel diambil ada 2 cara, yaitu nilai P dan IK.

Variabel adalah karakteristik subjek penelitian yang berubah antar subjek. Var perancu adalah variabel yang berhubungan dengan var bebas dan tergantung, tetapi bukan variabel perantara.

Tipe data: Data adalah hasil pengukuran. Pengukuran adalah proses kuantifikasi hasil observasi yang memperhatikan referensi tertentu dan dinyatakan dalam unit baku atau dianggap baku.

1.  skala kategorik
2.  skala numerik

skala kategoril a. skala nominal (tidak ada derajat yang superior inferior) b. skala ordinal (ada derajat tapi tidak bisa dikuantifikasi secara matematika)

Skala numerik a. skala interval: nilai nol tidak absolut (arbitrary) b. skaa ratio: nilai nol absolut

lainnya Kontinyu: ada desimal diskreet: tidak ada desimal contoh jumlah keluarga.

bebas vs tergantung (uji bivariat) Nominal vs nominal : chi kuadrat, uji fischer nominal (dikotom) vs numerik: uji T nominal (\>2 nilai) vs numerik Anova Numerik vs numerik: korelasi/regresi

Jika tidak ada sebab akibat, pakai korelasi. Jika ada sebab (var bebas) dan akibat (tergangunt) pakai regresi

Multivariat bebas vs tergantung numerik vs numerik : regresi multipel nominal, numerik vs nominal : regresi logistik

Data berpasangan: adalah data yang berasal dari orang/subjek yang sama atau subjek yang berbeda yang telah dilakukan matching. (ada before dan after)

Uji parametrik: a. koef varians: \<30% b. uji K-S atau S-W

Uji homogenitas varians Uji levans

Uji non-parametrik

Interpretasi nilai P: 0,035 besarnya kemungkinan untuk memperileh hasil tersebut disebabkan oleh faktor peluang bila H0 benar adalah sebesar 3,5%. Artinya 96,5% lainnya adalah akibat faktor obat.

bila sampel kecil, nilai P bisa bermakna tetapi interval kepercayaan melewati nilai batas tidak signifikan.

## Study About Risk Factor/Case Control Study

Start from dependent variable to independent variable. Harus jelas bagaiamna kita memilih kasus dan kontrolnya.


## Study About DIagnosis

## Study about Therapy

## Study about Prognosis

## Summary Capita Selekta
