# Gastroenterology & Hepatology


## Gastroenterology

### Anorectal Disease

composed of blood vessels, smooth muscle ﬁbers, and supporting connec-
tive tissue, normally present in the anal canal. The term “hem-orrhoids” is also applied to situations when these cushions become symptomatic.

Hemorrhoids are the result of slippage of the anal cushions due to weakening of the supporting tissues. The prolapse hinders the venous ﬂow leading to dilatation and engorge-ment of the anal cushions, exposing them to complications such as edema, thrombosis, and bleeding.

Hemorrhoids are classiﬁed as internal, external, or combined. Internal hemorrhoids are located proximal to the dentate line and are covered by insensate columnar mucosa or transitional epithelium. External hemorrhoids are located below the dentate line, covered with squamous epithelium rich in nerve endings.

#### Clinical Presentation
The most common clinical presentation are;

1. Bleeding per rectum.
2. Prolapsing tissue.

Bleeding per rectum is The bleeding is bright red and painless, and it usually follows evacuation. 

Prolapse occurs during straining or heavy lifting causing dis-comfort, feeling of incomplete evacuation, mucus discharge, and pruritus. Prolapsing hemorrhoids can be complicated by incarceration and strangulation secondary to thrombosis, causing severe pain and requiring urgent surgery. 

Internal hemorrhoids are classiﬁed according to the degree of prolapse: 

1. Grade I – bleeding without prolapse; 
2. Grade II – prolapse on straining that spontaneously reduces; 
3. Grade III – prolapse that requires manual reduction; and 
4. Grade IV – irreducible prolapse

External hemorrhoids are usually asymptomatic unless thrombosis develops, which is frequently due to trauma and straining. They present as a painful blue lump at the anal verge.

Patients older than 40 years or with atypical symptoms should undergo complete colonic investigation to exclude cancer. Inﬂammatory bowel disease is marked by bloody diarrhea

#### Treatment

Medical treatment aims to promote soft, formed, regular bowel movements:
1. with a high-ﬁber diet (20–30 g/day). bulking agents (psyllium husk: e.g., Metamucil™, 1 packet 1–3 times/day) 

2. generous water intake (six 8-ounce glasses of water/day). 

3. Warm sitz baths are helpful to relax the anal sphincter.

## Hepatology