# Metodologi Penelitian

## Overview of Clinical Research

clinical research is medical research taht involves people, to learn more about disease and improve health care for people in the future.

include: epidemiology, behavioral, health services, clinical trials.

clinical research, not just clinical trial, it is any research design that studies humans or any materials taken from humans. it may even include animal studies that the results apply to humans.

type of clinical research:

-   observational studies =\> studies that aim to identify and analylyze patterin medical data.
-   clinical trials/interventional studies

Research Question: FINER - Feasible - interesting - novel - ethical - relevant

## Association & Causation

Sebuah hubungan belum tentu menunjukan sebab-akibat. Banyak peneliti menghindari dgmatic statement: "cause" or "produces"

Causation: occurs when a change in one variable produces a change in another variable

-   Contributory Cause, no single specific cause of a disease. Most of disease cause by multifactorial etiologies. A risk factor may a contributory cause.

Three criteria: 1. Association may be reflected by effect size 2. Prior Association, does the cause (independent var) precede the effects (dependent var) (case control or cohort), 3. Altering the cause alters the effects

Some other features of contributory causation:

1.  Consistency: the results of study (effect size) should be consistent regardless the design, the population used.

2.  Dose response relathionsip

3.  Biologic Plausibility: should make biologic sense.

4.  Experimental confirmation: phenomenon found in lcinical studies have to be consistent with studies in animal models.

-   Necessary cause, dibuktikan sebagai satu satunya penyebab. Sebagai contoh: fullfiled by Koch's Postulates: the organism is always found with the disease.

Association: can be observed between many variable, but causaton only be determined from data collected from a controlled experiment.

-   Spurious association, association no actually present in population 3 mekanisme spurious causation

    -   Chance, due to random error and sampling variation (Individual chance to be a sample not equal), karakteristik sampel terlalu heterogen. Minimize random error: adequate sample size and low type 1 and type 2 error. Effect of random error can be judged from the width of the 95% confidence interval and the consistency of the results with previous evidence.

    -   Design, conduct of the study, and analyze of the results,

        -   selection bias, pemilihan sampel yg tidak sesuai =\> randomized and blind intervention
        -   performance bias, pemberian intervensi tidak setara antar sampel =\> randomized and blind intervention
        -   Detection bias, deteksi efek atau cause tidak sama =\> randomized and blind intervention
        -   Transfer bias, loss to follow up

    -   Confounding, occurs when factors which related to both independent and dependent variables. Contoh Kopi menyebabkan AMI, tetapi ada faktor merokok dimana orang ngopi juga suka merokok. Ternyata merokok yang berhubungan dgn AMI, tetapi merokok tidak berhubungan dengan AMI. Kontrol dengan by design atau by analysis.

-   Real Association, true biological phenomena. However not due to a cause effect relationship

**Critical Appraisal about Harm/Etiology/Causation.** follow checklist.

PR: 1 jenis penelitian causation atau association yang menjadi ide kalian nanti penelitian.

## Research Measurement

## Variables and Relathionship Between Variables

Variable: independent, dependent, confounding variables

other variable: mediator, moderator, external, random

relathioships among variables

-   chances
-   bias
-   confounding
-   causal

## Hypothesis and Hypothesis Testing

Hypothesis:

a statement about relathionsip between two or more variables that suggest an answer to the research question, is declarative statement that predicts an expected outcome.

Research hypothesis: kalimat deklaratif yang mencoba memberikan jawaban sementara atas pertanyaan penelitian.

Statistical hypotesis: biasanya tidak ditulis di proposal.

Research hypothesis nanti akan di uji apakah hypotesis didukukng oleh data data.

Jika hypotesis yang kita uji tidak sesuai dengan data, maka bukan berarti ilmu itu salah

## Sample Size and Power

Sample size pentingnya untuk bisa mewakili populasi dan dapat inferensi ke populasi itu kembali, serta:

- untuk mendeteksi treatment effects jika memang ada di populasi (mendapatkan hasil statistik signifikan dan secara klinis penting)
- Presisi estimasi
- avoid wasting resources
- avoid misleading conclusion

**Two many subject proves everything, too few subject proves nothing**

Kapan ketika perhitungan sample size tidak diperlukan?
 - Penelitian kualitatif
 - Pilot studi, biasanya 10 -20 subjek untuk menentukan sample size studi yang lebih besar.
 
 Sampel size sesuai dengan design, analysis plan dan outcome. Sample size harus sesuai untuk memenuhi statistical significance dan clinically important, tanpa membuang sumber daya terlalu banyak.
 
Sampel size berhubungan power. Power = makin kuat penelitian mampu mendeteksi sebuah efek di populasi, maka semakin banyak sample size dibutuhkan.
 
Definition of Power: the probability of concluding the new treatment is effective if it truly is effective. Biasanya 80%
type I error = the probability of concluding that the new treatment is effective if it truly is not effective. (positive palsu, alpha)
type II error = the probability of concluding the new treatment not effective if it is truly effective (negative palsu, 1 - power atau beta)

Elemen menentukan sample size:
$\Delta$ = **effect size** or difference under null hypotesis (perbedaan klinis yang dianggap penting) diambil dari studi sebelumnya dan tinjauan pustaka. Jika effect size besar, maka sampel di butuhkan lebih kecil, begitu kebalikannya
$\alpha$ = type I error, 0,05
$\beta$ = type 2 error, 0,2
$\sigma$ = standard deviation, makin heterogen populasi maka sample size makin besar.
r = ratio of number of patients in the two groups, usually  r = 1

Hubungan sampel size dengan hasil presisi, dimana hasil confidence interval akan lebih sempit (lebih presisi) jika sample size besar.
Jika hipotesis 2 arah, sample lebih besar, biasanya lebih disarankan hipotesis 2 arah.
Pertimbangan tambahan sampel jika kemungkinan loss to follow up terutama pada kohort prospektif dan clinical trial. Jika cross sectional, tidak perlu.
Jika tidak ada studi sebelumnya sebagai patokan sampel, maka tetap harus memperhitungkan sampel dengan cara pilot study.

Jika tidak bisa memenuhi jumlah sampel sesuai perhitungan sebelum penelitian (apriori), kita bisa mennetukan apakah hasil studi kita underpower dengan memperhitungkan hasil tes post-hoc.

Stategi meminimalkan sample size
- pakai varibael kontinyu
- paired measurement.

rule of thumb: 10 - 50 per variabel, atau 30 sampel. Pakai rule of thumb jika tidak ada data yang bisa mendukung perhitungan jumlah sampel.

Effect size tidak boleh mengutip dari penelitian lain secara *eksplisit* di proposal.

## Effect Size, Confident Interval, and P Value

## Research Design

## Cross Sectional and Case Control

## Cohort Study

## Experiments

## Diagnostic Test

## Data Management and Analysis

## Research Proposal

## Ethical Issue

## Novelty Aspect
