# Nefrology & urology

## Nefrology

### Hypertension

### FLuid and Electrolyte Disorders

#### Disorders of Extracelular Volume

#### Disorders of Water Metabolism

#### Disorders of Potassium Metabolism

The most frequent electrolyte abnormalities in clinical medicine.Patients with disor-ders of potassium metabolism may be asymptomatic, or they may have symptoms ranging from mild weakness to sudden death.

##### Normal Physiology

###### Potassium Intake

Potassium is necessary for essentially all cellular functions, is present in most foods, and is excreted primarily by the kidney. Typical diet 70 mmol of potassium, while the recommended intake is 120 mmol per day. Gastrointestinal tract efficiently absorbs potassium.

###### Potassium Distribution

After absorption from the GI tract, potassium distributes rapidly into the extracellular fluid (ECF) and intracellular fluid (ICF) compartments. Cellular potassium uptake is rapid and limits the magnitude of changes in serum potassium concentration. During potassium deficiency, shift of potassium from intracellular to extracellular compartments limits the change in extracellular potassium concentration.

Most potassium is in the ICF. Most body potassium is intracellular, with only 1% to 2% in the ECF. Potassium is the major intracellular cation, with cytosolic K+ concentrations about 100 to 120 mmol/L. Total intracellular K+ content is 3000 to 3500 mmol in healthy adults and is found primarily in muscle (70%), with a lesser amount in bone, red blood cells, liver, and skin.

###### Renal Handling of Potassium in Normal Kidney

###### Renal Potassium Handling in Chronic Kidney Disease

##### Hypokalemia

##### Hyperkalemia

#### Disorders of Calcium, Phosphate and Magnesium Metabolism

#### Acid-Base Balance

##### Metabolic Acidosis

##### Metabolic Alkalosis

##### Respiratory Acidosis

##### Respiratory Alkalosis

##### Mixed Acid Base Balance

### Infectious Disease in Kidney

### Acute Kidney Injury

### GLomerular Disease

### Tubulointerstitial Disease

### Diabetic Kidney Disease

### Renovascular Disease

### Hepatorenal Syndrome

### Cardiorenal Syndrome

### Pregnancy and Renal Disease

### Congenital Disease of the Kidney

### Chronic Kidney Disease

### Dialytic Therapy

### Transplantation

### Edema and Diuretics use

##### Diuretics Type

Diuretics are based on the sites of action. These are as follows:

![The proximal tubule (PT, purple segment) is represented by a typical PT cell. The loop of Henle (LH) includes a thick ascending limb (TAL, green segment), and a typical TAL cell is shown in green. The distal convoluted tubule (DCT, blue segment) is represented by a typical DCT cell in blue. The collecting duct (CD, yellow and orange segments) includes principal cells (PC), shown in yellow.](image/diuretics.png){#fig-diuretics fig-align="center"}

##### Proximal Tubular Diuretics

Carbonic Anhydrase inhibitor (CAI) work by inhibiting generation of intracellular Hidrogen ion, which is a requirement for absorption of natrium. This is the main action for its diuretics property. Most of the work in proximal tubule where bulk of natrium absorption, although Na absorption in more distal tubule will reduce CAI effects. Acetazolamide is the only diuretics used in practice. Asetasolamide has short action, due to ready absorbed and easily eliminated by tubular action. Prolonged used will cause metabolic acidosis, thus **acetazolamied 250 to 500 mg** daily used to correct metabolic alkalosis as side effects of thiazide or loop diuretics. Its use shouldbe cautiously in advanced kidney disease as it will systemically accumulates with repeat dosing.

##### Distal Convoluted Tubule Diuretics

The major site of action of thiazide diuretics is the early DCT where they inhibit the coupled reabsorption of Na+ and chloride (Cl−). Thiazides also :

1.  inhibit NaCl/fluid reabsorption in the medullary-collecting duct.
2.  The water-soluble thiazides such as hydrochlorothiazide (HCTZ) also inhibit CA when given at high doses, and therein further increase Na+ excretion.
3.  thiazide diuretics impair urinary diluting capacity without affecting urinary concentrating mechanisms,
4.  reduce calcium (Ca++) and urate excretion,
5.  increase magnesium (Mg++) excretion
6.  thiazide diuretic to minimize the development of loop diuretic--related DCT cell hypertrophy that might otherwise increase Na+ absorption

The onset of diuresis with hidrochlorotiazid (HCTZ) occurs within 2 hours, peaks between 3 and 6 hours, and dose-dependently continues for upward to 12 hours. The half-life (t 12) of HCTZ is prolonged both in decompensated HF and kidney failure. Doses of thiazide diuretics in the **100 to 200 mg/day** range are required to initiate a diuresis in patients with chronic **kidney disease (CKD)**, although the overall natriuretic response is arbitrated by the GFR/filtered Na+ load.

A newer thiazid diuretis are chlorthalidone. chlorthalidone and HCTZ are structurally similar, they differ pharmacokinetically in that chlorthalidone has a longer t 12 of 40 to 60 hours versus 3.2 to 13.1 hours for HCTZ, as well as a larger volume of distribution by virtue of its extensive partitioning into red blood cells. This latter feature creates a depot that promotes continuous streaming of chlorthalidone (red cell → plasma → tubular secretion). This plasma half-life dif-ference for chlorthalidone correlates with a more extended diuretic effect and is a likely explanation for the observation that chlorthalidone is a better mg-for-mg antihypertensive than HCTZ.

##### Loop Diuretics

Loop diuretics act predominantly at the luminal membrane in the thick ascending limb (TAL) of the loop of Henle where they compete with Cl− for binding to the Na+/K+/2Cl− cotransporter, thereby inhibiting Na+ and Cl− reabsorption. Loop diuretics also:

1.  a decrease in both free water (H2O) excretion and absorption during H2O loading and dehydration, respectively,

2.  a 30% increase in fractional Ca++ excretion, a significant increase in Mg++ excretion,

3.  brief increase followed by a more long-lived decrease in uric acid excretion.

4.  Stimulate renal prostaglandin synthesis, particularly that of the vasodilatory prostaglandin E2 (PGE2).

Angiotensin-II, generated following the administration of intravenous loop diuretics, coupled with an increased synthesis of PGE2, are the likely reasons for the shift in renal blood flow (RBF) from the inner to the outer renal cortex with these drugs; however, both total RBF and GFR are maintained when loop diuretics are administered to normal subjects. Loop diuretics are highly protein bound, therefore to gain access to their tubular site of action they must be secreted as is the case for thiazide diuretics. Tubular secretion of loop diuretics may be interfered by elevated levels of endogenous organic acids, as arise in CKD, and by drugs that share the same transporter site, such as salicylates and nonsteroidal antiinflammatory drugs (NSAIDs). Uremic toxins and fatty acids can decrease loop diuretic protein binding and further alter diuretic pharmacokinetics.

Furosemide is the most widely used diuretic in this class; however, its use is complicated by variable absorption with a bioavailability ranging from 12% to 112%. The coefficient of variation for absorption varies from 25% to 43% for different furosemide products, and exchanging one furosemide. formulation for another will not standardize patient absorption and/or response to oral furosemide. Loop diuretics are commonly used in the patient with CKD, with the renal clearance of these drugs reduced in parallel with the degree of reduction in kidney function. In general, furosemide pharmacokinetics are more significantly changed in CKD than the other loop diuretics, with both its renal metabolism and intact clearance reduced in CKD.

##### Distal Potassium-Sparing Diuretics

There are two classes of K+-sparing diuretics: competitive antagonists of aldosterone, such as spironolactone or eplerenone, and compounds that work independent of aldosterone, such as amiloride and triamterene. Drugs in this class reduce active Na+ absorption in the late DCT/collecting duct (CD). Basolateral Na+/K+-ATPase activity reduced, intracellular K+ concentration decreases, and the electrochemical gradient for K+ is lowered, thereby reducing K+ secretion. K+-sparing diuretics also reduce Ca++ and Mg++ excretion, which is a useful feature in the HF patient. Because K+-sparing diuretics are only modestly natriuretic, their clinical utility resides more in their K+-sparing capacity, particularly when more proximally acting diuretics increase distal Na+ delivery or in the instance of either primary or secondary aldosteronism.

Spironolactone is a well-absorbed, highly protein-bound, lipid-soluble K+-sparing diuretic with a 20-hour half-life. The onset of action for spironolactone is characteristically slow, with a peak response at times 48-hours or more after the initial dose. Spironolactone, unlike amiloride and triamterene, remains active (as a diuretic and antihypertensive agent) in advanced kidney failure in that its locus of action is basolateral; thus it does not require glomerular filtration or tubular secretion to gain access to its effect site. Eplerenone is a mineralocorticoid receptor antagonist that is highly selective for the aldosterone receptor; accordingly, its much lower affinity for androgen and progesterone receptors results in considerably less gynecomastia than is the case with spironolactone.

##### Osmotic Diuretics

Mannitol is a polysaccharide diuretic given intravenously that is freely eliminated by glomerular filtration. Mannitol is poorly reabsorbed along the length of the nephron and thereby exerts a dose-dependent osmotic effect. This osmotic effect traps water and solutes in the tubular fluid, thus increasing Na+, K+, Cl−, and HCO3− excretion. The plasma half life mannitol depends on the level of kidney function but usually is between 30 and 60 minutes; thus its diuretic properties are quite transient. Mannitol has been used to reduce the incidence of acute kidney injury (AKI) in patients undergoing cardiopulmonary bypass, having rhabdomyolysis, or following exposure to contrast media. mannitol also expands extracellular fluid (ECF) volume and can precipitate pulmonary edema in patients with HF, it should be used cautiously, if at all, in these patients. excessive mannitol administration, particularly in the setting of a reduced GFR, can cause dilutional hyponatremia, hyperkalemia, and/or AKI. The latter is dose dependent, relates to afferent arteriolar vasoconstriction, and commonly corrects with the elimination of excess mannitol as may be accomplished with hemodialysis.

#### Edema Treatment

The pathophysiology of Na+ and H2O retention in the patient with edema is typically characterized by a complex interchange of hemodynamic and neurohumoral factors. For example, systemically perceived arterial underfilling sets into motion related Na+ and H2O retention in the patient with HF. In other instances, such as in the patient with a reduced GFR and/or nephrotic syndrome, Na+ and H2O retention derives from a more primary set of renal processes. There are two important considerations that should be brought to bear before and/or concurrent with initiation of diuretic therapy: the need to restrict dietary Na+ intake (2 to 4 g Na+ day) and dose reduction/elimination of drugs that foster Na+ retention, such as NSAIDs, nonspecific vasodilators like hydralazine and minoxidil, and high-dose β-blockers or central α-agonists.

A compound, such as chlorthalidone, can be quite effective in the setting of mild to moderate edema given once or twice daily in the 25- to 50-mg/day range. When the underlying disease state worsens and/or dietary Na+ restriction cannot be adequately maintained, then conversion to a loop diuretic--based regimen becomes the more practiced approach. Combination diuretic therapy can be considered thereafter, either because the severity of the edema requires "sequential nephron blockade" or because the underlying disease state is particularly sensitive to medications other than loop diuretics, as is the case for spironolactone (50 → 400-mg/day range) use in the patient with advanced cases of cirrhosis and ascites.

Determining the minimally effective dose for a diuretic effect is a necessary clinical exercise, particularly in the patient with a reduced GFR. Gradually increasing a diuretic dose until a response is seen will establish the threshold/ effect dose, and thereafter the frequency of dosing can be established based on clinical circumstances. The beginning dose from which dose titration proceeds is influenced by both the level of kidney function and the severity of the edematous state. If kidney function is reduced, the diuretic dose-response curve shifts to the right and the maximal effectiveness, based on absolute Na+ excretion rate, can be significantly reduced, therein making dietary Na+ restriction of considerable importance. In CKD patients with edema furosemid 40 mg twice daily would be considered adequate starting doses that could then be gradually incremented until the desired effect is achieved. Often, the dose that elicits an increase in urine output can be continued indefinitely unless the underlying disease state worsens and/or dietary Na+ intake becomes inordinately high. Conversely, a diuretic dose that establishes "euvolemia" can occasionally be lowered and restriction of dietary Na+ intake given added opportunity to minimize edema redevelopment. Diuretic dose reduction should always be a sought after consideration, as it minimizes loss of K+, Mg++, and, in the case of loop diuretics, Ca++.

##### Adaptation to Diuretic Therapy

Diuretic-induced inhibition of Na+ reabsorption in one nephron segment elicits important adaptations in other nephron segments, which not only limits their antihypertensive and fluid-depleting actions but also contributes to the development of side effects. The initial dose of a diuretic normally produces a brisk diuresis, which is quickly followed by a new equilibrium state in which daily fluid and electrolyte excretion either matches or is less than intake with body weight stabilizing. In nonedematous patients given either a thiazide or a loop diuretic, this adaptation, or **braking phenomenon**, occurs within 1 to 2 days and limits net weight loss to 1 to 2 kg.

![Effect of a loop diuretic on urinary sodium (Na ) excretion. Each bar represents a 6-hour time interval. Purple bars indicate periods during which urinary Na+ excretion (UNaV) exceeds that of dietary intake. Blue areas indicate periods of postdiuretic Na+ retention, during which dietary Na+ intake exceeds urinary Na+ excretion. The horizontal black line indicates dietary Na+ intake per 24-hour period. Changes in the magnitude of the natriuretic response over several days are reflective of the "braking phenomenon." Inset shows the effect of diuretics on weight (and extracellular fluid volume) during several days of diuretic administration.](image/natriuresis.png){#fig-natriuresis fig-align="center"}

For example, furosemide administered orally to subjects ingesting a high-Na+ diet (270 mmol/24 hours) produced an initial brisk natriuresis, which resulted in a negative Na+ balance over the ensuing 6 hours. This was followed by an 18-hour period when Na+ excretion was reduced to levels well below the prescribed Na+ intake, resulting in a positive Na+ balance. This postdiuresis Na+ retention matched the initial natriuresis with the result at the end of the day being a neutral Na+ balance state and no weight loss. After 3 successive days of furosemide administration, a similar pattern of Na+ loss and retention was demonstrated each day. if Na+ intake is kept very low, balance can remain negative after a single dose of furosemide, even though there is some blunting of the initial natriuretic response.

![(A) Comparison of effects of chronic kidney disease (CKD) and conditions marked by edema on the loop diuretic dose response, expressed as fractional Na+ excretion (FENa). Diuretic delivery via secretion into the lumen is impaired in CKD (pharmacokinetic abnormal- ity), whereas the response to delivered drug is diminished with edema (pharmacodynamic defect). (B) Effect of CKD on the absolute response to a loop diuretic. Compare with panel A. (C) Pharmacokinetics of intravenous and oral loop diuretics. The diuretic thresholds for normal and edematous individuals are shown as horizontal lines; whereas a normal individual responds appropriately to either an intravenous or oral diuretic, some edematous individuals can only reach threshold excretion with intravenous diuretic administration.](image/ckd_diuretics.png){#fig-ckddiuretics fig-align="center"}

The mechanistic basis for the braking phenomenon is complex. The relationship between natriuresis and the rate of furosemide excretion is shifted to the right in subjects receiving a low-salt diet, which denotes a blunting of tubular response. It appears to be unrelated to aldosterone, as spironolactone therapy has little effect on the Na+ retention. Structural hypertrophy in the distal nephron also occurs in rats receiving prolonged infusions of loop diuretics. These structural changes are marked by increased distal nephron Na+ and Cl− absorption and K+ secretion, phenomena which are aldosterone independent. These structural adaptationsmay contribute to postdiuretic Na+ retention and to diuretic tolerance in humans, and could explain the **Na+ retention persisting for up to 2 weeks after loop diuretic therapy is discontinued**.

Plasma renin activity (PRA) and plasma aldosterone concentrations rise within minutes of receiving an intravenous diuretic, a transient process that is independent of volume loss and/or sympathetic nervous system (SNS) activation. This rise in PRA is caused by inhibition of NaCl reabsorption at themacula densa in conjunction with loop-diuretic stimulation of renal prostaglandin release. Shortly after this initial rise in PRA, diuretics cause a more sustained increase in PRA and aldosterone arising from an increase in SNS activity (β-agonism) anda fall in ECF volume. The increase in renal prostaglandin production is the likely explanation for the preload reduction and decrease in ventricular filling pressures that occur within 15 minutes of loop diuretic administration.

## Urology
