# Statistik Kedokteran Dasar

## Dasar-dasar Penulisan Ilmiah Kedokteran dan Plagiarisme

Metode sains: bisa diulang dengan hasil yang sama. observasi, measurement, verification and evaluation (self correction)

## Kiat-kiat Publikasi Majalah Terakreditasi dengan OJS

Kendala Publikasi di Indonesia: - Indonesia lack of language access. Why we dont make one in Bahasa Indonesia? - Lack of Cultural backgroud dalam menulis.

Kenapa publikasi penting? - Rekognisi atas hasil penelitian anda baik pengakuan regional, nasional dan internasional - H Index - Jaminan kolaborasi di tingkat regional, nasional, dan internasional

Publikasi:

-   Submit ke jurnal dgn OJS
-   Jika ditolak, edit ulang dan perbaiki.

Perlu diketahui: - Penulisan naskah/manuskrip ilmiah merupakan suatu tangtangan, seni dan kemampuan mengelaborasi hasil penelitian. - Ikuti kaidah IMRAD. Introduction biasanya sudah menggambarkan M,R,D nya.

Author vs Behavior

-   Author
    -   Want to publish more, write in detail
-   Reader
    -   want to read less. (judul yg baik)
    -   Want integrated system
    -   Browsing is crucial
    -   Quality information is important
    -   Want to read less

Unsur Utama dalam Publikasi: - Isue Etik + pernyataan tidak ada conflict of interest + Pencantuman sumber dana + Image manipulation guidelines

-   Gaya Selingkung dan Bahasa
    -   Sesuai author guidelines
-   Struktur naskah/manuskrip ilmiah
    -   Title: judul clear, precise, including keywords. do not use abbreviations and jargon
    -   Authors Listing: only include those who have made an intelectual contribution to the research, or those who will publicly defend the data and conclusion, and who have approved the final version. Gift (atasan, dekan, kepala lab), Guest (pemberi dana), and Ghost author (ini tidak boleh, atas dasar sembarangan mengikutkan namanya).Ghost writer, penulis lain yg menawarkan jasa (secara etika diijinkan).
    -   Abstract: ditulis selesai IMRAD. Tidak boleh sebelum lengkap dan menyeluruh menulis IMRAD. Bisa terjadi inkonsistensi dgn discussion.
    -   Introduction: clearly state the problem being investigated, background that explains the problem, reasons for conducting the research. Summarize relevant research to provide context. State how your work differs from published work. Identify the questions you are answering.
    -   Methods: Jika RCT sebaiknya diregister, agar SOP penelitian bisa dibaca orang lain dan terrekognisi. PRovide the readers enough details so they can understand and replicate your research. Explain how you studied the problemm identify procedures, order the chronologically where possible. Include the frequency of observations, what types of data were recorded.
    -   Results: -- to be continued
    -   Discussion: -- to be continued
    -   Conclusion: -- to be continued
-   Submit artikel/pemilihan jurnal
-   proses publikasi/peer review

Dulu hierarki tertinggi evidence adalah: Validitas Pada Penelitian Randomized, controlled, clinical trial.

Validitas Internal

-   Ada kontrol
-   Ada Randomisasi

Validitas External

-   loss to follow up \< 20%?

Saat ini sudah bergeser pada Systematic Review dan Metanalysis.

## Effect Size, COnfidence Interval

## Uji Hipotesis

Mengacu pada distribusi populasi:

Asumsi dasar H0; u1 = u2 (hipotesis nol,tidak ada perbedaan) H1: u1 =/ u2 (hipotesis alternatif, ada perbedaan)

H1 diterima bila terjadi kesalahan kecil: kesalahan tipe 1, false positivie : dihitung peluang kesalahan akibat variasi sampel =\> nilai P batas penolakan (alpha) 0,05;0,01

-   beta: kesalahan tipe 2, false negative: ditetapkan
-   metafor: seperti persidangan

Jenis Hipotesis: - superiority testing: A lebih baik daripada B - non-inferirority: membuktukan perbedaan dalam rentang yang tak berbeda. (contoh penelitian obat biosimilar)

makna p value - chance play a role in sample value if H0 accepted

significant level (alpha) if p\< 0.05 or 0.01 as cut off dicari: power(1-beta) di set di awal 80% atau 90% ditentukan the answer yes or no tetapi tidak bisa melihat seberapa.... sehingga saat ini tidak hanya boleh melihat P value, karena harus melihat effect size dengan confidence interval.

menghitung confifdence interval :

### Clinician and Statistician

Nilai P tidak memberikan informasi besar perbedaan hasil (effect size) beda yang kecil saja memberikan signifikansi statsitik bila N besar

beda yang besar bisa tidak memberikan signifikansi statistik bila N kecil (error type 2)

Maka perlu ukuran sampel yang sesuai, dan perlu memaknai sebuah statistical significance dengan makna klinis (clinical importance)

## Korelasi Linier

Dasar-dasar dan aplikasi biostatistika klinik

- mengestimasi kuatnya hubungan atau besarnya perbedaan (besarnya efek)
- melakukan uji kemaknaan statistik (inferensial)
- mengontrol pengaruh variable pengganggu terhadap besar efek dan inferensi

hubungan semu dapat diperoleh dari analissis bivariat, lalu multivariat untuk mengekslusi hubungan semu.

Korelasi = antara independen dan dependennya memiliki hubungan garis lurus.
Korelasi ada 2, liner dan non linier. Korelasi ada fleksibilitas variabel independen dan dependennya.

Jenis analisis statistik:
-  Tentukan pertama parametrik atau non-parametrik
-  Skala variabel: kontinyu (variabel skala dan interval), ordinal, nominal, diskriit
-  Uji normalitas: normal/non normal (tes kolmogorov smirnov atau shapiro-wilk)
-  Uji kesamaan varisi: sama/tidak sama (uji levene)
-  Uji kolinearitas: hubungan antar variabel independen (penting untuk uji partial korelasi, regresi linier berganda)

variabel: 
- jika bisa dipecah menjadi 5 atau lebih, bisa dikatakan continyu.
- jika kontinyu dipecah menjadi beberapa kategori : bisa ordinal
- jika yes no= nominal
- diskrit = tidak bisa dibedakan antara kategori?

Pemilihan uji statistik:
1. tentukan variabel dependen (umumnya satu variable dependen)
2. tentukan jumlah variabel independen
    - bila tidak ada variabel independen, statistik yang dipakai adalah analisis univariat (deskriptif)
    - bila ada satu variabel independen, statistik yang dipakai adalah bivariat
    - bila ada lebih dari satu variable independen, statistik yang dipakai adalah analisis multivariat.
    
Sentral limit theorem: jika lebih dari 30 bisa berdistribusi normal.

```{r}
DiagrammeR::grViz("
                  digraph {
                  graph[layout=dot, rankdir=TB, fontsize=10]
                  
                  # Node
                  
                  
                  
                  # Edges
                  
                  }
                  ")
```



## Regresi Linier Sederhana

## Regresi Berganda

## Distribusi normal

## Uji T berpasangan dan tak berpasangan

## One Way ANOVA

## Ancova dan Repeated Measurements ANOVA

## Tabel 2 x 2, Odd ratio, Prevalence Ratio dan Relative Risk

## Prinsip Analisis Data Biner

## Regresi Logistik Sederhana

## Regresi Logistik Berganda
